permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-suspend args
permit nopass nolog emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-call
permit nopass nolog emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-sms args
permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-network
permit nopass nolog emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-wifi-connect args
permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-device args status
permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-device args brightness 25
permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-device args brightness 50
permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-device args brightness 75
permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-device args brightness 100
permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-device args flashlight on
permit nopass emacsos-lab as root cmd /usr/local/sbin/emacsos-openrc-device args flashlight off
