;;; test-swipe-learning.el --- Swipe learning control tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'swipe-learning)

(ert-deftest emacsos-swipe-learning-erase-is-in-buffer-two-tap ()
  (let ((called nil))
    (cl-letf (((symbol-function 'pop-to-buffer)
               (lambda (buffer &rest _) (set-buffer buffer)))
              ((symbol-function 'emacsos-swipe-learning--run)
               (lambda (command _progress &optional success)
                 (if (equal command "erase-ready")
                     (funcall success '((message . "Erase is ready")) "{}")
                   (setq called command)))))
      (emacsos-swipe-learning-erase)
      (with-current-buffer emacsos-swipe-learning--buffer
        (should (string-match-p "Erase learning data" (buffer-string)))
        (button-activate (next-button (point-min)))
        (should (string-match-p "Confirm erase" (buffer-string)))
        (button-activate (next-button (point-min)))))
    (should (equal called "erase"))))

(ert-deftest emacsos-swipe-learning-unrelated-command-disarms-erase ()
  (cl-letf (((symbol-function 'pop-to-buffer)
             (lambda (buffer &rest _) (set-buffer buffer)))
            ((symbol-function 'emacsos-swipe-learning--run)
             (lambda (_command _progress &optional success)
               (funcall success '((message . "Erase is ready")) "{}"))))
    (emacsos-swipe-learning-erase)
    (with-current-buffer emacsos-swipe-learning--buffer
      (button-activate (next-button (point-min)))
      (emacsos-swipe-learning--post-command-disarm)
      (emacsos-swipe-learning--post-command-disarm)
      (should-not emacsos-swipe-learning--erase-armed)
      (should (string-match-p "Erase learning data" (buffer-string)))
      (should-not (string-match-p "Confirm erase" (buffer-string))))))

(ert-deftest emacsos-swipe-learning-commands-use-fixed-helper-arguments ()
  (let (captured
        (emacsos-swipe-learning--process nil))
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) nil))
              ((symbol-function 'pop-to-buffer) (lambda (&rest _)))
              ((symbol-function 'make-process)
               (lambda (&rest arguments)
                 (setq captured arguments)
                 'fake-process)))
      (emacsos-swipe-learning-enable)
      (should (equal (plist-get captured :command)
                     (list emacsos-swipe-learning--helper "enable")))
      (should (eq (plist-get captured :connection-type) 'pipe)))))

(ert-deftest emacsos-swipe-learning-stale-results-are-ignored ()
  (let ((emacsos-swipe-learning--operation 4)
        (output (generate-new-buffer " *swipe-learning-stale-test*"))
        displayed)
    (unwind-protect
        (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
                  ((symbol-function 'process-exit-status) (lambda (_) 0))
                  ((symbol-function 'process-buffer) (lambda (_) output))
                  ((symbol-function 'emacsos-swipe-learning--display)
                   (lambda (text) (setq displayed text))))
          (emacsos-swipe-learning--finish 'fake "finished" 3 nil))
      (when (buffer-live-p output) (kill-buffer output)))
    (should-not displayed)
    (should-not (buffer-live-p output))))

(ert-deftest emacsos-swipe-learning-malformed-success-output-is-identified ()
  (let ((emacsos-swipe-learning--operation 4)
        (output (generate-new-buffer " *swipe-learning-malformed-test*"))
        displayed)
    (with-current-buffer output
      (insert "not-json"))
    (unwind-protect
        (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
                  ((symbol-function 'process-exit-status) (lambda (_) 0))
                  ((symbol-function 'process-buffer) (lambda (_) output))
                  ((symbol-function 'emacsos-swipe-learning--display)
                   (lambda (text) (setq displayed text))))
          (emacsos-swipe-learning--finish 'fake "finished" 4 nil))
      (when (buffer-live-p output) (kill-buffer output)))
    (should (equal displayed "Swipe learning returned malformed output."))))

(ert-deftest emacsos-swipe-learning-does-not-interrupt-live-helper ()
  (let ((emacsos-swipe-learning--process 'active)
        displayed)
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'delete-process)
               (lambda (_) (ert-fail "must not interrupt helper")))
              ((symbol-function 'emacsos-swipe-learning--display)
               (lambda (text) (setq displayed text))))
      (emacsos-swipe-learning-disable))
    (should (equal displayed "A learning operation is already in progress."))))

(ert-deftest emacsos-swipe-learning-launch-failure-is-visible ()
  (let (displayed
        (emacsos-swipe-learning--process nil))
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) nil))
              ((symbol-function 'pop-to-buffer) (lambda (&rest _)))
              ((symbol-function 'make-process) (lambda (&rest _) (error "missing")))
              ((symbol-function 'emacsos-swipe-learning--display)
               (lambda (text) (setq displayed text))))
      (emacsos-swipe-learning-enable))
    (should (string-match-p "could not start: missing" displayed))))
