;;; test-swipe-learning.el --- Swipe learning control tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'swipe-learning)

(ert-deftest emacsos-swipe-learning-erase-is-in-buffer-two-tap ()
  (let ((called nil)
        (emacsos-swipe-learning--buffer nil))
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'pop-to-buffer)
                     (lambda (buffer &rest _) (set-buffer buffer)))
                    ((symbol-function 'emacsos-swipe-learning--run)
                     (lambda (command _progress &optional success)
                       (if (equal command "erase-ready")
                           (funcall success '((message . "Erase is ready")) "{}")
                         (setq called command)))))
            (emacsos-swipe-learning-erase)
            (with-current-buffer emacsos-swipe-learning--buffer
              (should (string-match-p "Erase learning data" (buffer-string)))
              (button-activate (next-button (point-min)))
              (should (string-match-p "Confirm erase" (buffer-string)))
              (button-activate (next-button (point-min)))))
          (should (equal called "erase")))
      (when (buffer-live-p emacsos-swipe-learning--buffer)
        (kill-buffer emacsos-swipe-learning--buffer)))))

(ert-deftest emacsos-swipe-learning-unrelated-command-disarms-erase ()
  (let ((emacsos-swipe-learning--buffer nil))
    (unwind-protect
        (cl-letf (((symbol-function 'pop-to-buffer)
                   (lambda (buffer &rest _) (set-buffer buffer)))
                  ((symbol-function 'emacsos-swipe-learning--run)
                   (lambda (_command _progress &optional success)
                     (funcall success '((message . "Erase is ready")) "{}"))))
          (emacsos-swipe-learning-erase)
          (with-current-buffer emacsos-swipe-learning--buffer
            (button-activate (next-button (point-min)))
            (emacsos-swipe-learning--post-command-disarm)
            (emacsos-swipe-learning--post-command-disarm)
            (should-not emacsos-swipe-learning--erase-armed)
            (should (string-match-p "Erase learning data" (buffer-string)))
            (should-not (string-match-p "Confirm erase" (buffer-string)))))
      (when (buffer-live-p emacsos-swipe-learning--buffer)
        (kill-buffer emacsos-swipe-learning--buffer)))))

(ert-deftest emacsos-swipe-learning-commands-use-fixed-helper-arguments ()
  (let (captured
        (emacsos-swipe-learning--process nil))
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) nil))
              ((symbol-function 'pop-to-buffer) (lambda (&rest _)))
              ((symbol-function 'emacsos-swipe-learning--display) (lambda (&rest _)))
              ((symbol-function 'make-process)
               (lambda (&rest arguments)
                 (setq captured arguments)
                 'fake-process)))
      (emacsos-swipe-learning-enable)
      (should (equal (plist-get captured :command)
                     (list emacsos-swipe-learning--helper "enable")))
      (should (eq (plist-get captured :connection-type) 'pipe)))))

(ert-deftest emacsos-swipe-learning-controls-preserve-colliding-user-buffer ()
  (let ((emacsos-swipe-learning--buffer nil)
        (collision (generate-new-buffer emacsos-swipe-learning--buffer-name))
        called changed)
    (unwind-protect
        (progn
          (with-current-buffer collision
            (setq-local major-mode 'vterm-mode)
            (setq-local mode-name "vterm")
            (insert "user sentinel")
            (add-hook 'change-major-mode-hook (lambda () (setq changed t)) nil t)
            (setq buffer-read-only t))
          (should (equal (buffer-name collision)
                         emacsos-swipe-learning--buffer-name))
          (cl-letf (((symbol-function 'pop-to-buffer) (lambda (&rest _)))
                    ((symbol-function 'emacsos-swipe-learning--run)
                     (lambda (command _progress &optional success)
                       (push command called)
                       (if success
                           (funcall success '((message . "ok")) "{}")
                         (emacsos-swipe-learning--display "result")))))
            (with-current-buffer collision
              (emacsos-swipe-learning-enable)
              (emacsos-swipe-learning-show)
              (emacsos-swipe-learning-disable)
              (emacsos-swipe-learning-erase))
            (let ((first-owned emacsos-swipe-learning--buffer))
              (should (buffer-live-p first-owned))
              (should-not (eq first-owned collision))
              (with-current-buffer first-owned
                (should (eq major-mode 'emacsos-swipe-learning-mode))
                (should (string-match-p "Erase learning data" (buffer-string)))
                (button-activate (next-button (point-min)))
                (should (string-match-p "Confirm erase" (buffer-string)))
                (button-activate (next-button (point-min))))
              (should (equal (nreverse called)
                             '("enable" ("--page" "0" "show") "disable"
                               "erase-ready" "erase")))
              (with-current-buffer collision
                (should (equal (buffer-string) "user sentinel"))
                (should (eq major-mode 'vterm-mode))
                (should (equal mode-name "vterm"))
                (should buffer-read-only))
              (should-not changed)
              (kill-buffer first-owned)
              (with-current-buffer collision
                (emacsos-swipe-learning--arm-erase nil)
                (emacsos-swipe-learning-enable))
              (should (buffer-live-p emacsos-swipe-learning--buffer))
              (should-not (eq emacsos-swipe-learning--buffer first-owned))
              (with-current-buffer collision
                (should (equal (buffer-string) "user sentinel"))
                (should (eq major-mode 'vterm-mode))
                (should (equal mode-name "vterm"))
                (should buffer-read-only))
              (should-not changed)))
      (when (buffer-live-p emacsos-swipe-learning--buffer)
        (kill-buffer emacsos-swipe-learning--buffer))
      (when (buffer-live-p collision)
        (kill-buffer collision))))))

(ert-deftest emacsos-swipe-learning-stale-results-are-ignored ()
  (let ((emacsos-swipe-learning--operation 4)
        (output (generate-new-buffer " *swipe-learning-stale-test*"))
        displayed)
    (unwind-protect
        (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
                  ((symbol-function 'process-exit-status) (lambda (_) 0))
                  ((symbol-function 'process-buffer) (lambda (_) output))
                  ((symbol-function 'emacsos-swipe-learning--display)
                   (lambda (text) (setq displayed text))))
          (emacsos-swipe-learning--finish 'fake "finished" 3 nil))
      (when (buffer-live-p output) (kill-buffer output)))
    (should-not displayed)
    (should-not (buffer-live-p output))))

(ert-deftest emacsos-swipe-learning-malformed-success-output-is-identified ()
  (let ((emacsos-swipe-learning--operation 4)
        (output (generate-new-buffer " *swipe-learning-malformed-test*"))
        displayed)
    (with-current-buffer output
      (insert "not-json"))
    (unwind-protect
        (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
                  ((symbol-function 'process-exit-status) (lambda (_) 0))
                  ((symbol-function 'process-buffer) (lambda (_) output))
                  ((symbol-function 'emacsos-swipe-learning--display)
                   (lambda (text) (setq displayed text))))
          (emacsos-swipe-learning--finish 'fake "finished" 4 nil))
      (when (buffer-live-p output) (kill-buffer output)))
    (should (equal displayed "Swipe learning returned malformed output."))))

(ert-deftest emacsos-swipe-learning-does-not-interrupt-live-helper ()
  (let ((emacsos-swipe-learning--process 'active)
        displayed)
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'delete-process)
               (lambda (_) (ert-fail "must not interrupt helper")))
              ((symbol-function 'emacsos-swipe-learning--display)
               (lambda (text) (setq displayed text))))
      (emacsos-swipe-learning-disable))
    (should (equal displayed "A learning operation is already in progress."))))

(ert-deftest emacsos-swipe-learning-launch-failure-is-visible ()
  (let (displayed
        (emacsos-swipe-learning--process nil))
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) nil))
              ((symbol-function 'pop-to-buffer) (lambda (&rest _)))
              ((symbol-function 'make-process) (lambda (&rest _) (error "missing")))
              ((symbol-function 'emacsos-swipe-learning--display)
               (lambda (text) (setq displayed text))))
      (emacsos-swipe-learning-enable))
    (should (string-match-p "could not start: missing" displayed))))
