;;; test-conversation-rendering.el --- Native local object regressions -*- lexical-binding: t -*-
(require 'ert)
(require 'chat)
(require 'emacsos-typography)

(defconst rendering-test--table
  "| Item | kcal | P | C | F |\n|------|------|---|---|---|\n| 1 slice bread + Kite Hill cream cheese + nutritional yeast | 236 | 10g | 27g | 9g |\n| ½ chocolate croissant | 110 | 2.5g | 14g | 6g |\n| ½ small coffee cake | 125 | 2g | 17.5g | 5.5g |\n| **Total** | **470** | **15g** | **59g** | **20g** |\n| 界 | 1 | 2 | 3 | 4 |\n")

(ert-deftest rendering-paths-map-only-the-current-workspace ()
  (let ((root (make-temp-file "render-workspace" t))
        (outside (make-temp-file "render-outside" t)))
    (unwind-protect
        (progn
          (write-region "one" nil (expand-file-name "notes.md" root) nil 'silent)
          (write-region "two" nil (expand-file-name "notes.md" outside) nil 'silent)
          (make-symbolic-link outside (expand-file-name "escape" root))
          (make-directory (expand-file-name ".git" root))
          (write-region "private" nil (expand-file-name ".git/config" root) nil 'silent)
          (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory)
                     (lambda () root)))
            (dolist (path '("notes.md" "/user/notes.md" "/workspace/notes.md"))
              (should (equal (emacsos-conversation--local-file path) (expand-file-name "notes.md" root))))
            (dolist (path '("../notes.md" "escape/notes.md" "/tmp/notes.md" ".git/config" "/etc/passwd" "/ssh:host:/etc/passwd" "missing.md"))
              (should-not (emacsos-conversation--local-file path))))
          (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () outside)))
            (should (equal (emacsos-conversation--local-file "notes.md") (expand-file-name "notes.md" outside)))))
      (delete-directory root t) (delete-directory outside t))))

(ert-deftest rendering-files-use-explicit-local-objects-and-preserve-source ()
  (with-temp-buffer
    (emacsos--chat-enable-presentation)
    (insert "bot> Here:\n```render\ntype: file\npath: /workspace/notes.md\nlines: 2-4\n```\n[notes](/user/notes.md)\n```render\ntype: map\npin: 1,2 x\n```\n> unsent draft")
    (let ((source (buffer-substring-no-properties (point-min) (point-max))))
      (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () nil)))
        (emacsos--chat-present-message 1 6 (- (point-max) 14) 'assistant))
      (should (equal source (buffer-substring-no-properties (point-min) (point-max))))
      (goto-char (point-min)) (search-forward "```render")
      (should (equal (get-text-property (match-beginning 0) 'emacsos-conversation-object)
                     '(file "/workspace/notes.md" "2-4")))
      (should (string-match-p "Unavailable locally" (get-text-property (match-beginning 0) 'display)))
      (search-forward "notes]")
      (should (equal (get-text-property (- (point) 3) 'emacsos-conversation-object)
                     '(file "/user/notes.md" nil)))
      (search-forward "type: map")
      (should-not (get-text-property (match-beginning 0) 'display))
      (let ((kill-ring nil))
        (kill-ring-save (point-min) (point-max))
        (should (equal (car kill-ring) source))))))

(ert-deftest rendering-example-table-aligns-unicode-and-keeps-return-draft ()
  (save-window-excursion
    (let ((source (generate-new-buffer " *render-conversation*")) view)
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (emacsos--chat-enable-presentation)
            (insert "bot> " rendering-test--table "\n> unfinished draft")
            (let ((original (buffer-substring-no-properties (point-min) (point-max))))
              (emacsos--chat-present-message 1 6 (- (point-max) 18) 'assistant)
              (goto-char 6)
              (should (eq (car (get-text-property (point) 'emacsos-conversation-object)) 'table))
              (emacsos-conversation--open-object)
              (setq view (current-buffer))
              (should truncate-lines) (should-not word-wrap)
              (should (equal (lookup-key (current-local-map) (kbd "C-c b")) #'emacsos-conversation-table-back))
              (let (positions)
                (goto-char (point-min))
                (while (not (eobp))
                  (let (columns)
                    (while (search-forward "|" (line-end-position) t)
                      (push (current-column) columns))
                    (push (nreverse columns) positions))
                  (forward-line 1))
                (should (cl-every (lambda (row) (equal row (car positions))) positions)))
              (emacsos-conversation-table-scroll-right)
              (should (= (window-hscroll) 12))
              (should header-line-format)
              (emacsos-conversation-table-back)
              (should (eq (current-buffer) source))
              (should-not truncate-lines)
              (should (equal original (buffer-substring-no-properties (point-min) (point-max))))))
        (when (buffer-live-p view) (kill-buffer view)) (kill-buffer source)))))

(ert-deftest rendering-fences-isolate-nested-objects-and-representation-refresh ()
  (with-temp-buffer
    (insert "```text\n```render\ntype: file\npath: notes.md\n```\n" rendering-test--table "\n" rendering-test--table)
    (emacsos--chat-present-markdown-1 (point-min) (point-max))
    (goto-char (point-min)) (search-forward "type: file")
    (should-not (get-text-property (point) 'emacsos-conversation-object))
    (goto-char (point-min)) (search-forward "| Item")
    (should (get-text-property (match-beginning 0) 'emacsos-conversation-object))
    (let ((start (match-beginning 0)))
      (search-forward "| Item")
      (should (get-text-property (match-beginning 0) 'emacsos-conversation-object))
      (goto-char start)
      (delete-region start (progn (forward-line 1) (point)))
      (emacsos--chat-present-markdown-1 (point-min) (point-max))
      (should-not (get-text-property start 'display)))))

(ert-deftest rendering-png-checks-bounded-actual-bytes-before-decoding ()
  (let ((file (make-temp-file "render-image" nil ".png")) seen)
    (unwind-protect
        (progn
          (let ((coding-system-for-write 'no-conversion))
            (write-region (base64-decode-string "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1sAAAAASUVORK5CYII=") nil file nil 'silent))
          (cl-letf (((symbol-function 'display-images-p) (lambda (&rest _) t))
                    ((symbol-function 'create-image) (lambda (data type &rest _) (setq seen (list data type)) '(image))))
            (should (equal (emacsos-conversation--png file) '(image)))
            (should (eq (cadr seen) 'png))
            (should (equal (substring (car seen) 1 4) "PNG"))
            (let ((data (copy-sequence (car seen))) (coding-system-for-write 'no-conversion))
              (aset data 16 127)
              (write-region data nil file nil 'silent))
            (setq seen nil)
            (should-not (emacsos-conversation--png file))
            (should-not seen)))
      (delete-file file))))


(ert-deftest rendering-link-opener-rechecks-current-file-and-suppresses-svg-decoding ()
  (let ((root (make-temp-file "render-open" t)) opened mode range)
    (unwind-protect
        (progn
          (write-region "<svg/>" nil (expand-file-name "drawing.svg" root) nil 'silent)
          (with-temp-buffer
            (insert "[drawing](/workspace/drawing.svg)")
            (emacsos--chat-present-markdown-1 (point-min) (point-max))
            (goto-char 2)
            (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root))
                      ((symbol-function 'emacsos-assist-web-find-file)
                       (lambda (file) (setq opened file mode (assoc-default file auto-mode-alist #'string-match)))))
              (emacsos-conversation--open-object)
              (should (equal opened (expand-file-name "drawing.svg" root)))
              (should (eq mode 'fundamental-mode))
              (delete-file opened)
              (setq opened nil)
              (emacsos-conversation--open-object)
              (should-not opened))))
      (delete-directory root t))))

(ert-deftest rendering-huge-alignment-does-not-amplify-small-source ()
  (save-window-excursion
    (let* ((source (concat "| A | B |\n|---|---|\n| " (make-string 10000 ?a) " | b |\n"
                           (apply #'concat (make-list 100 "| a | b |\n"))))
           view)
      (unwind-protect
          (progn
            (emacsos-conversation--table-view source)
            (setq view (current-buffer))
            (should (< (buffer-size) (+ (length source) 100)))
            (should (string-prefix-p "Table exceeds alignment limit" (buffer-string))))
        (when view (kill-buffer view))))))

(ert-deftest rendering-markdown-budget-clears-old-native-display ()
  (with-temp-buffer
    (emacsos-markdown-mode)
    (insert rendering-test--table)
    (jit-lock-fontify-now)
    (should (get-text-property 1 'display))
    (goto-char (point-max))
    (insert (make-string emacsos--chat-presentation-max-bytes ?x))
    (jit-lock-fontify-now)
    (should-not (get-text-property 1 'display))
    (should-not (get-text-property 1 'emacsos-conversation-object))))


(ert-deftest rendering-indented-fence-keeps-separate-targets-and-prose ()
  (with-temp-buffer
    (insert "  ```render\ntype: file\npath: first.md\n  ```\nVisible prose\n```render\ntype: file\npath: second.md\n```\n")
    (emacsos--chat-present-markdown-1 (point-min) (point-max))
    (should (equal (get-text-property 1 'emacsos-conversation-object) '(file "first.md" nil)))
    (goto-char 1) (search-forward "Visible prose")
    (should-not (get-text-property (match-beginning 0) 'display))
    (search-forward "second.md")
    (should (equal (get-text-property (match-beginning 0) 'emacsos-conversation-object) '(file "second.md" nil)))))

(ert-deftest rendering-table-header-controls-select-clicked-window ()
  (save-window-excursion
    (let ((prose (generate-new-buffer " *render-prose*")) view table-window prose-window)
      (unwind-protect
          (progn
            (switch-to-buffer prose) (insert "wrapped prose")
            (setq prose-window (selected-window))
            (emacsos-conversation--table-view rendering-test--table)
            (setq view (current-buffer) table-window (selected-window))
            (setq prose-window (split-window table-window nil 'below))
            (set-window-buffer prose-window prose)
            (select-window prose-window)
            (let ((last-input-event (list 'mouse-1 (list table-window 'header-line '(0 . 0) 0))))
              (emacsos-conversation-table-scroll-right))
            (should (eq (selected-window) table-window))
            (should (= (window-hscroll table-window) 12))
            (should (= (window-hscroll prose-window) 0))
            (should-not auto-hscroll-mode))
        (when view (kill-buffer view)) (kill-buffer prose)))))

(ert-deftest rendering-real-local-opener-preserves-file-bytes-and-rejects-file-eval ()
  (require 'assist-web)
  (save-window-excursion
    (let* ((root (make-temp-file "render-real-open" t))
           (file (expand-file-name "notes.el" root))
           (source (generate-new-buffer " *render-file-source*")) view
           (rendering-test-evaluated nil)
           (safe-local-eval-forms '((setq rendering-test-evaluated t))))
      (unwind-protect
          (progn
            (write-region (concat ";;; notes\n;; Local " "Variables:\n;; eval: (setq rendering-test-evaluated t)\n;; End:\n") nil file nil 'silent)
            (switch-to-buffer source)
            (insert "[notes](</workspace/notes.el:2>)")
            (emacsos--chat-present-markdown-1 1 (point-max))
            (goto-char 2)
            (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root)))
              (emacsos-conversation--open-object))
            (setq view (current-buffer))
            (should (equal buffer-file-name file))
            (should (= (line-number-at-pos) 2))
            (should-not rendering-test-evaluated)
            (should-not (buffer-modified-p)))
        (when (and view (not (eq view source))) (kill-buffer view))
        (kill-buffer source) (delete-directory root t)))))


(ert-deftest rendering-repeated-and-distinct-pngs-share-whole-buffer-budget ()
  (let ((root (make-temp-file "render-budget" t)) (decodes 0))
    (unwind-protect
        (progn
          (let* ((data (concat (base64-decode-string "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1sAAAAASUVORK5CYII=")
                               (make-string 700000 0)))
                 (coding-system-for-write 'no-conversion))
            (write-region data nil (expand-file-name "one.png" root) nil 'silent)
            (write-region data nil (expand-file-name "two.png" root) nil 'silent))
          (with-temp-buffer
            (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root))
                      ((symbol-function 'display-images-p) (lambda (&rest _) t))
                      ((symbol-function 'create-image)
                       (lambda (data type &rest _) (cl-incf decodes) (list 'image :type type :data data))))
              (dotimes (_ 1000) (insert "```render\ntype: file\npath: one.png\n```\n"))
              (emacsos--chat-present-markdown-1 1 (point-max))
              (should (= decodes 1))
              (should (eq (car (get-text-property 1 'display)) 'image))
              (goto-char (point-max))
              (let ((start (point)))
                (insert "```render\ntype: file\npath: two.png\n```\n")
                (emacsos--chat-present-markdown-1 start (point-max))
                (should (= decodes 1))
                (should (stringp (get-text-property start 'display)))))))
      (delete-directory root t))))

(ert-deftest rendering-angle-urls-stay-http-and-other-schemes-inert ()
  (with-temp-buffer
    (insert "[site](<https://example.org>) [bad](<javascript:alert>) [details](#details)")
    (emacsos--chat-present-markdown-1 1 (point-max))
    (should (equal (get-text-property 2 'emacsos-conversation-url) "https://example.org"))
    (should-not (get-text-property 2 'emacsos-conversation-object))
    (goto-char 1) (search-forward "bad")
    (should-not (get-text-property (match-beginning 0) 'emacsos-conversation-object))
    (should-not (get-text-property (match-beginning 0) 'emacsos-conversation-url))
    (search-forward "details")
    (should-not (get-text-property (match-beginning 0) 'emacsos-conversation-object))
    (should-not (get-text-property (match-beginning 0) 'keymap))))


(ert-deftest rendering-invalid-png-attempts-remain-bounded-across-transcript-messages ()
  (let ((root (make-temp-file "render-invalid" t)) (reads 0)
        (reader (symbol-function 'insert-file-contents-literally)))
    (unwind-protect
        (progn
          (write-region (make-string 700000 ?x) nil (expand-file-name "invalid-0.png" root) nil 'silent)
          (dotimes (index 20)
            (unless (= index 0)
              (add-name-to-file (expand-file-name "invalid-0.png" root)
                                (expand-file-name (format "invalid-%d.png" index) root))))
          (with-temp-buffer
            (dotimes (index 20)
              (insert (format "bot> ```render\ntype: file\npath: invalid-%d.png\n```\n" index)))
            (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root))
                      ((symbol-function 'display-images-p) (lambda (&rest _) t))
                      ((symbol-function 'insert-file-contents-literally)
                       (lambda (&rest args) (cl-incf reads) (apply reader args))))
              (emacsos--chat-present-transcript 1 (point-max)))
            (should (= reads 1))))
      (delete-directory root t))))

(ert-deftest rendering-markdown-copy-excludes-native-object-properties ()
  (with-temp-buffer
    (emacsos-markdown-mode)
    (insert rendering-test--table)
    (jit-lock-fontify-now)
    (let ((kill-ring nil))
      (kill-ring-save (point-min) (point-max))
      (should (equal (car kill-ring) rendering-test--table))
      (should-not (text-properties-at 0 (car kill-ring))))))


(ert-deftest rendering-fallback-images-open-literally-without-decoding ()
  (require 'assist-web)
  (save-window-excursion
    (let ((root (make-temp-file "render-fallback" t))
          (source (generate-new-buffer " *render-fallback-source*"))
          (decoded nil) view)
      (unwind-protect
          (progn
            (let ((data (base64-decode-string "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1sAAAAASUVORK5CYII="))
                  (coding-system-for-write 'no-conversion))
              (aset data 18 16) (aset data 22 16)
              (write-region data nil (expand-file-name "large.png" root) nil 'silent)
              (write-region "GIF89a" nil (expand-file-name "other.gif" root) nil 'silent))
            (dolist (name '("large.png" "other.gif"))
              (switch-to-buffer source)
              (erase-buffer)
              (insert (format "[image](%s)" name))
              (emacsos--chat-present-markdown-1 1 (point-max))
              (goto-char 2)
              (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root))
                        ((symbol-function 'image-mode) (lambda () (setq decoded t) (fundamental-mode))))
                (emacsos-conversation--open-object))
              (setq view (current-buffer))
              (should (equal buffer-file-name (expand-file-name name root)))
              (should (eq major-mode 'fundamental-mode))
              (should-not decoded)
              (should-not (buffer-modified-p))
              (kill-buffer view) (setq view nil)))
        (when view (kill-buffer view))
        (kill-buffer source) (delete-directory root t)))))

(ert-deftest rendering-repeated-pngs-reuse-one-display-across-messages ()
  (let ((root (make-temp-file "render-message-cache" t)) (decodes 0) (reads 0)
        (reader (symbol-function 'insert-file-contents-literally)))
    (unwind-protect
        (progn
          (let ((coding-system-for-write 'no-conversion))
            (write-region
             (concat (base64-decode-string "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1sAAAAASUVORK5CYII=")
                     (make-string 700000 0))
             nil (expand-file-name "one.png" root) nil 'silent))
          (with-temp-buffer
            (dotimes (_ 20) (insert "bot> ```render\ntype: file\npath: one.png\n```\n"))
            (let ((source (buffer-string)) first)
              (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root))
                        ((symbol-function 'display-images-p) (lambda (&rest _) t))
                        ((symbol-function 'insert-file-contents-literally)
                         (lambda (&rest args) (cl-incf reads) (apply reader args)))
                        ((symbol-function 'create-image)
                         (lambda (data type &rest _) (cl-incf decodes) (list 'image :type type :data data))))
                (dotimes (pass 3)
                  (emacsos--chat-present-transcript 1 (point-max))
                  (should (= reads (1+ pass))) (should (= decodes (1+ pass)))
                  (setq first nil)
                  (goto-char 1)
                  (while (search-forward "```render" nil t)
                    (let ((display (get-text-property (match-beginning 0) 'display)))
                      (should (eq (car-safe display) 'image))
                      (if first (should (eq display first)) (setq first display))))))
              (should (equal source (buffer-substring-no-properties 1 (point-max)))))))
      (delete-directory root t))))

(ert-deftest rendering-table-keeps-open-separator-and-short-row-columns ()
  (save-window-excursion
    (let ((source (generate-new-buffer " *render-short-table*")) view)
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (insert "| A | B | C |\n|---|---|---\n| a | b | c |\n| short |\n")
            (let ((original (buffer-string)))
              (emacsos--chat-present-markdown-1 1 (point-max))
              (goto-char 1)
              (should (get-text-property 1 'emacsos-conversation-object))
              (emacsos-conversation--open-object)
              (setq view (current-buffer))
              (goto-char 1)
              (let (positions)
                (while (not (eobp))
                  (let (columns)
                    (while (search-forward "|" (line-end-position) t)
                      (push (current-column) columns))
                    (should (= (length columns) 4))
                    (push (nreverse columns) positions))
                  (forward-line 1))
                (should (cl-every (lambda (row) (equal row (car positions))) positions)))
              (emacsos-conversation-table-back)
              (should (equal original (buffer-substring-no-properties 1 (point-max))))))
        (when view (kill-buffer view)) (kill-buffer source)))))


(ert-deftest rendering-compressed-file-link-preserves-bounded-stored-bytes ()
  (require 'assist-web)
  (require 'jka-compr)
  (save-window-excursion
    (let* ((root (make-temp-file "render-compressed" t))
           (file (expand-file-name "drawing.svgz" root))
           (source (generate-new-buffer " *render-compressed-source*")) view stored)
      (unwind-protect
          (progn
            (write-region (concat "<svg>" (make-string (* 2 1024 1024) ?x) "</svg>") nil file nil 'silent)
            (should (< (file-attribute-size (file-attributes file)) 4096))
            (with-temp-buffer
              (set-buffer-multibyte nil)
              (insert-file-contents-literally file)
              (setq stored (buffer-string)))
            (switch-to-buffer source)
            (insert "[drawing](drawing.svgz)")
            (emacsos--chat-present-markdown-1 1 (point-max))
            (goto-char 2)
            (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root)))
              (emacsos-conversation--open-object))
            (setq view (current-buffer))
            (should (equal buffer-file-name file))
            (should (eq major-mode 'fundamental-mode))
            (should (= (buffer-size) (length stored)))
            (should (equal (buffer-string) stored))
            (should-not (buffer-modified-p)))
        (when (and view (not (eq view source))) (kill-buffer view))
        (kill-buffer source) (delete-directory root t)))))


(ert-deftest rendering-mapped-remote-paths-never-reach-filesystem ()
  (let ((root (make-temp-file "render-no-remote" t)) probed)
    (unwind-protect
        (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root))
                  ((symbol-function 'file-in-directory-p) (lambda (&rest _) (setq probed t) nil))
                  ((symbol-function 'file-symlink-p) (lambda (&rest _) (setq probed t) nil))
                  ((symbol-function 'file-regular-p) (lambda (&rest _) (setq probed t) nil)))
          (dolist (path '("/workspace//ssh:host:/etc/passwd" "/user//ssh:host:/etc/passwd"))
            (setq probed nil)
            (should-not (emacsos-conversation--local-file path))
            (should-not probed)))
      (delete-directory root t))))

(ert-deftest rendering-existing-image-and-compressed-visits-remain-untouched ()
  (require 'assist-web)
  (save-window-excursion
    (let ((root (make-temp-file "render-existing" t))
          (source (generate-new-buffer " *render-existing-source*")) existing)
      (unwind-protect
          (progn
            (let ((coding-system-for-write 'no-conversion))
              (write-region (base64-decode-string "R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7")
                            nil (expand-file-name "visited.gif" root) nil 'silent))
            (write-region (concat "<svg>" (make-string (* 2 1024 1024) ?x) "</svg>")
                          nil (expand-file-name "visited.svgz" root) nil 'silent)
            (make-symbolic-link (expand-file-name "visited.svgz" root) (expand-file-name "alias.svgz" root))
            (dolist (pair '(("visited.gif" . "visited.gif") ("visited.svgz" . "visited.svgz") ("alias.svgz" . "visited.svgz")))
              (setq existing (find-file-noselect (expand-file-name (car pair) root)))
              (when (string-suffix-p ".svgz" (car pair))
                (with-current-buffer existing
                  (should (> (buffer-size) (* 1024 1024)))))
              (let ((original (with-current-buffer existing (buffer-string)))
                    (mode (buffer-local-value 'major-mode existing)))
                (switch-to-buffer source)
                (erase-buffer)
                (insert (format "[file](%s)" (cdr pair)))
                (emacsos--chat-present-markdown-1 1 (point-max))
                (goto-char 2)
                (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root)))
                  (emacsos-conversation--open-object))
                (should (eq (current-buffer) source))
                (should (buffer-live-p existing))
                (should (eq (buffer-local-value 'major-mode existing) mode))
                (with-current-buffer existing
                  (should (equal original (buffer-string)))
                  (should-not (buffer-modified-p))))
              (kill-buffer existing) (setq existing nil)))
        (when existing (kill-buffer existing))
        (kill-buffer source) (delete-directory root t)))))

(ert-deftest rendering-table-back-releases-temporary-snapshot ()
  (save-window-excursion
    (let ((source (generate-new-buffer " *render-table-lifetime*")) view)
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (insert rendering-test--table "\n> unsent draft")
            (emacsos--chat-present-markdown-1 1 (point-max))
            (goto-char 1)
            (let ((original (buffer-substring-no-properties 1 (point-max)))
                  (initial (cl-count-if (lambda (b) (string-prefix-p "*Assist table*" (buffer-name b))) (buffer-list))))
              (dotimes (_ 20)
                (emacsos-conversation--open-object)
                (setq view (current-buffer))
                (emacsos-conversation-table-back)
                (should (eq (current-buffer) source))
                (should-not (buffer-live-p view))
                (should (= initial (cl-count-if (lambda (b) (string-prefix-p "*Assist table*" (buffer-name b))) (buffer-list)))))
              (should (equal original (buffer-substring-no-properties 1 (point-max))))))
        (when (buffer-live-p view) (kill-buffer view))
        (kill-buffer source)))))


(ert-deftest rendering-symlink-checks-never-invoke-remote-handlers ()
  (let ((root (make-temp-file "render-symlink-handler" t)) calls issue result)
    (unwind-protect
        (progn
          (make-symbolic-link "/ssh:host:/etc/passwd" (expand-file-name "escape.md" root))
          (cl-letf (((symbol-function 'emacsos-assist-web-git-local-directory) (lambda () root)))
            (let ((file-name-handler-alist
                   (cons (cons "\\`/ssh:host:.*\\'"
                               (lambda (operation &rest _args)
                                 (push operation calls)
                                 (error "Unexpected remote handler")))
                         file-name-handler-alist)))
              (condition-case problem
                  (setq result (emacsos-conversation--local-file "escape.md"))
                (error (setq issue problem)))))
          (should-not issue) (should-not calls) (should-not result))
      (delete-directory root t))))

(provide 'test-conversation-rendering)
