#!/usr/bin/env bash
# phone-bringup.sh — install WireGuard on the phone, generate a keypair (the
# private key stays on the phone), write /etc/wireguard/wg0.conf with the
# operator-supplied peer info, and enable + bring up wg-quick@wg0.
#
# Run ON THE PHONE, as root (the `wg-phone-bringup` Make target scp's this
# here and runs it with the right env).
#
# Parameters arrive as KEY=VALUE lines on STDIN — never argv/env — so secrets
# can't leak into the phone's process table:
#     SERVER_PUBKEY     (required) WG server's public key
#     WG_ENDPOINT       (required) e.g. [2001:db8::abcd]:51821 (use a stable v6
#                        endpoint so the phone reaches it on both wifi and
#                        T-Mobile cellular; v4 only works on wifi)
#     WG_ADDR           (required) phone's wg-subnet IP, e.g. 10.0.0.X/32
#     WG_ALLOWED_IPS    (optional) required (the wg subnet, plus optionally the server LAN IP);
#                        if you want the chat URL to route via wg both at home
#                        and away, include the server's LAN IP here as a /32.
#     PEER_LABEL        (optional, default "wg server") comment in the [Peer]
#                        block.
#
# Idempotent except for keypair generation: an existing keypair is preserved
# (re-running with different SERVER_PUBKEY/WG_ENDPOINT just rewrites wg0.conf
# around the same key — same identity to the server).  Sets MTU = 1280 (see
# the design doc's Decision 4 for why this is mandatory over cellular).

set -uo pipefail

# --- read KEY=VALUE params from stdin ---------------------------------------
SERVER_PUBKEY=""; WG_ENDPOINT=""; WG_ADDR=""; WG_ALLOWED_IPS=""; PEER_LABEL=""
while IFS='=' read -r key val || [ -n "$key" ]; do
  case "$key" in
    SERVER_PUBKEY)  SERVER_PUBKEY=$val ;;
    WG_ENDPOINT)    WG_ENDPOINT=$val ;;
    WG_ADDR)        WG_ADDR=$val ;;
    WG_ALLOWED_IPS) WG_ALLOWED_IPS=$val ;;
    PEER_LABEL)     PEER_LABEL=$val ;;
    "")             : ;;
    *)              echo "phone-bringup: ignoring unknown parameter: $key" ;;
  esac
done

die()  { echo "phone-bringup: error: $*" >&2; exit 1; }
note() { echo "phone-bringup: $*"; }

[ "$(id -u)" -eq 0 ]      || die "must run as root"
[ -n "$SERVER_PUBKEY" ]   || die "SERVER_PUBKEY is required (pipe via stdin)"
[ -n "$WG_ENDPOINT" ]     || die "WG_ENDPOINT is required (e.g. [v6]:51821)"
[ -n "$WG_ADDR" ]         || die "WG_ADDR is required (e.g. 10.0.0.X/32)"
WG_ALLOWED_IPS="${WG_ALLOWED_IPS:?WG_ALLOWED_IPS is required (e.g. "<wg-subnet>, <server-lan-ip>/32")}"
PEER_LABEL="${PEER_LABEL:-wg server}"

# --- 1) install wireguard ----------------------------------------------------
if command -v wg >/dev/null 2>&1 && command -v wg-quick >/dev/null 2>&1; then
  note "wireguard already installed (wg + wg-quick present)"
else
  note "installing wireguard"
  apt-get install -y -qq wireguard 2>&1 | tail -3
fi

# --- 2) generate keypair (preserve existing) ---------------------------------
install -d -m 700 /etc/wireguard
if [ -s /etc/wireguard/privatekey ] && [ -s /etc/wireguard/publickey ]; then
  note "keypair already exists in /etc/wireguard — keeping it"
else
  note "generating keypair under /etc/wireguard (mode 600, root-only)"
  ( umask 077; wg genkey > /etc/wireguard/privatekey )
  wg pubkey < /etc/wireguard/privatekey > /etc/wireguard/publickey
  chmod 600 /etc/wireguard/privatekey
  chmod 644 /etc/wireguard/publickey
fi

# --- 3) write wg0.conf (with the supplied peer info) -------------------------
# Done inside this root context: privatekey -> conf substitution happens here,
# the privkey never leaves the phone via stdout/argv/env.
PRIV=$(cat /etc/wireguard/privatekey)
cat > /etc/wireguard/wg0.conf <<EOF
# Generated by deploy/wireguard/phone-bringup.sh on $(date -Is).
# MTU = 1280 is the IPv6 minimum — mandatory for TCP-over-wg over T-Mobile
# cellular's smaller PMTU.  See docs/2026-05-31-wireguard-away-phone.org §4.
[Interface]
PrivateKey = $PRIV
Address = $WG_ADDR
MTU = 1280

[Peer]
# $PEER_LABEL
PublicKey = $SERVER_PUBKEY
Endpoint = $WG_ENDPOINT
AllowedIPs = $WG_ALLOWED_IPS
PersistentKeepalive = 25
EOF
chmod 600 /etc/wireguard/wg0.conf

# --- 4) bring up + enable on boot --------------------------------------------
# If wg0 is already up, bounce it so the new conf takes effect cleanly.
# (`wg syncconf` doesn't re-create the kernel socket, and the bind interface
# stays sticky — see the design doc's Decision 5 for why this matters when
# the endpoint family changes.)
if ip link show wg0 >/dev/null 2>&1; then
  note "wg0 already up — bouncing to apply new conf"
  wg-quick down wg0 2>&1 | tail -3
fi
note "bringing wg-quick@wg0 up (and enabling on boot)"
systemctl enable --now wg-quick@wg0 2>&1 | tail -3

sleep 3
note "----- wg0 state -----"
wg show wg0 | grep -E "interface|public key|listening|endpoint|allowed|handshake|transfer|keepalive|^$"
echo
note "----- wg0 link -----"
ip -o link show wg0 | sed 's/^/  /'

echo
echo "==============================================================="
echo "Phone's PUBLIC KEY (paste into the next step on the server):"
cat /etc/wireguard/publickey
echo "==============================================================="
echo
echo "Next: on the dev box (WG server), run:"
echo "  make wg-add-peer PEER_PUBKEY=<that-pubkey> PEER_WG_IP=${WG_ADDR} PEER_LABEL=phone"
echo
echo "Then verify from the dev box:  ping ${WG_ADDR%/*}   ssh phone-wg"
